-- MySQL Script generated by MySQL Workbench
-- Sat Jan  7 14:45:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`categorie` ;

CREATE TABLE IF NOT EXISTS `webshop`.`categorie` (
  `idcategorie` INT NOT NULL COMMENT '',
  `naam` VARCHAR(45) NULL COMMENT '',
  `omschrijving` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idcategorie`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`produkt` ;

CREATE TABLE IF NOT EXISTS `webshop`.`produkt` (
  `idprodukt` INT NOT NULL COMMENT '',
  `categorie` INT NULL COMMENT '',
  `prijs` VARCHAR(45) NULL COMMENT '',
  `merk` VARCHAR(45) NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `soort` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idprodukt`)  COMMENT '',
  INDEX `fk_produkt_categorie_idx` (`categorie` ASC)  COMMENT '',
  CONSTRAINT `fk_produkt_categorie`
    FOREIGN KEY (`categorie`)
    REFERENCES `webshop`.`categorie` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webshop`.`categorie`
-- -----------------------------------------------------
START TRANSACTION;
USE `webshop`;
INSERT INTO `webshop`.`categorie` (`idcategorie`, `naam`, `omschrijving`) VALUES (1, 'stofzuiger', NULL);
INSERT INTO `webshop`.`categorie` (`idcategorie`, `naam`, `omschrijving`) VALUES (2, 'wasmachine', NULL);
INSERT INTO `webshop`.`categorie` (`idcategorie`, `naam`, `omschrijving`) VALUES (3, 'tv', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `webshop`.`produkt`
-- -----------------------------------------------------
START TRANSACTION;
USE `webshop`;
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (1, 1, '300', 'Gazelle', '200ZX', 'mtb');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (2, 1, '299', 'Batavus', '100FD', 'mtb');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (3, 1, '400', 'Monteo', 'Hoover', 'mtb');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (4, 2, '1200', 'Batavus', '34GG', 'drie');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (5, 2, '1100', 'Union', '439ER', 'drie');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (6, 2, '500', 'Raleigh', 'ZZ', 'race');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (7, 3, '345', 'Union', '42LG', 'race');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (8, 3, '455', 'Batavus', '55RD', 'race');
INSERT INTO `webshop`.`produkt` (`idprodukt`, `categorie`, `prijs`, `merk`, `type`, `soort`) VALUES (9, 3, '677', 'Gazelle', '66rTX', 'nouja');

COMMIT;
